astronomy-commons/hats-import

- README.md
- pyproject.toml
Change the name of the dev dependencies to match the project templates and other projects, similar to astronomy-commons/hipscat#13.
Also updated the README to include instructions for installing with dev dependencies on Mac.
> Change dev dependencies name inline with project template

- pyproject.toml
- src/hipscat_import/run_import.py
Use tqdm for cleaner command line progress bar. Adds a progress bar for non-parallelized process steps, to make the user feel like something's happening.
> Improve progress reporting

- pyproject.toml
- src/hipscat_import/__init__.py
- src/hipscat_import/__main__.py
- src/hipscat_import/command_line_arguments.py
- src/hipscat_import/control.py
With this, you can execute the import tool with commands like:
```
> hipscat-import --help
or
> hc --help
```
> Add console entry points for import tool.

- src/.pylintrc
- src/hipscat_import/__init__.py
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/command_line_arguments.py
- src/hipscat_import/runtime_arguments.py
- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/catalog/test_arguments_commandline.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/catalog/test_resume_files.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/test_runtime_arguments.py
There are a handful of arguments that will be used for creating indexes and equijoin association tables. This pulls those arguments, their validation logic, and the provenance info generation into a parent class.
This should simplify the new classes, as well as reducing duplicated code (which pylint was VERY unhappy about).
> Prefactor for alternate table import arguments.

- tests/hipscat_import/conftest.py
When running a single test case, they can fail because no `dask_client` is instantiated, if there's no dask_client requested, but is implicity required for dask dataframe operations.
This requires a dask client fixture for all dask tests, even if `dask_client` is not among requested fixtures for the test case.
Also ups the default timeout, since 3 was pushing it for github workflows.
> Require dask_client if not requested.

- src/hipscat_import/association/arguments.py
- src/hipscat_import/association/run_association.py
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/index/arguments.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/margin_cache/margin_cache_arguments.py
- tests/hipscat_import/association/test_association_argument.py
- tests/hipscat_import/association/test_run_association.py
- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/catalog/test_file_readers.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/data/small_sky_object_catalog/catalog_info.json
- tests/hipscat_import/data/small_sky_source_catalog/catalog_info.json
- tests/hipscat_import/index/test_index_argument.py
- tests/hipscat_import/index/test_run_index.py
- tests/hipscat_import/margin_cache/test_arguments_margin_cache.py
Create catalog-type-specific metadata in the resulting `catalog_info.json` file.
Uses the new subclasses defined in https://github.com/astronomy-commons/hipscat/pull/101 , and requires hipscat v0.0.12
> Use type-specific catalog info

- .github/workflows/smoke-test.yml
- .github/workflows/testing-and-coverage.yml
- .github/workflows/type-checking.yml
- docs/guide/dask_on_ray.rst
- docs/index.rst
- pyproject.toml
- tests/conftest.py
- tests/hipscat_import/association/test_run_association.py
- tests/hipscat_import/conftest.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
Adds a command line option and pytest fixtures to re-run the whole unit test suite using a dask-on-ray client, instead of vanilla dask.
Notes:
- The association pipeline doesn't work currently on dask-on-ray. I'd rather just remove the whole pipeline than figure out why.
- Instead of having the ray-enabled pipeline in this repo, this just adds a page in the RTD. This avoids an additional package dependency.
- I imagine some of this could be re-used for LSDB testing, if we would like to support a dask-on-ray model there as well.
> Add unit tests for dask-on-ray.

- pyproject.toml
- tests/hipscat_import/margin_cache/test_margin_cache.py
makes `numpy` a required dependency and sets the version to be < 1.25.
closes #111 
we use `numpy < 1.25` because `numba` (new `hipscat` dependency) hasn't been updated to support 1.25 yet.
seems like `numpy==1.25` suport will be added to `numba==0.58`, which is due sometime in the next couple of months. ticket [here](https://github.com/numba/numba/issues/8698).
> make numpy required dependency

- pyproject.toml
- src/hipscat_import/catalog/file_readers.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- src/hipscat_import/soap/map_reduce.py
- tests/hipscat_import/soap/test_soap_resume_plan.py
Uses the new `file_io.load_parquet_to_pandas` method, and test-friendly pixel list construction of a `Catalog`.
> Refactor based on hipscat v0.1.2

- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/arguments.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/soap/conftest.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Related to issue #116 . Current behavior of the `resume` flag is kinda confusing.
> Invert default on resume check.

- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/resume_plan.py
- src/hipscat_import/soap/run_soap.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #125 
Uses consistent minimum length for tqdm description in pipeline stages.
This stops short of adding another wrapper around tqdm step progress initialization.
> Use minimum stage name formatting.

- pyproject.toml
Pin pandas version to before 2.1.0, on the theory that the new version is causing smoke test failures.
> Pin pandas version

- src/hipscat_import/pipeline.py
Includes the catalog name in the failure email, to give some more hints about where to look for failure logs.
> Add a tad more context for failure email.

- src/hipscat_import/index/arguments.py
- src/hipscat_import/margin_cache/margin_cache_arguments.py
- src/hipscat_import/soap/arguments.py
- tests/hipscat_import/catalog/test_file_readers.py
- tests/hipscat_import/index/test_index_argument.py
- tests/hipscat_import/margin_cache/test_arguments_margin_cache.py
- tests/hipscat_import/soap/test_soap_arguments.py
Uses new `hipscat.io.validation.is_valid_catalog` to check for basic catalog existence/validity for catalogs that are used for inputs to other import pipelines.
Note that the smoke test is currently failing after the release of the above method. This PR aims to address the failing test, as well as augment existing passing checks.
> Check for valid catalog directories.

- src/hipscat_import/margin_cache/margin_cache.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
mixes in the negative tree pixels into the margin cache pipeline when appropriate (every step except for the mapping stage) to allow for full coverage.
resolves #137 .
- calls `Catalog.generate_negative_tree_pixels()` and combines them with `partition_stats`.
- also creates a new test specifically to ensure that margin caching can create a pixel file for a zero data pixel (i.e. one that's not represented in the main catalog partitions).
> add the negative tree pixels to margin cache pipeline

- src/hipscat_import/margin_cache/margin_cache_arguments.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
In preparation for addressing https://github.com/astronomy-commons/hipscat/issues/142, this removes the `get_pixels` method in favor of `get_healpix_pixels` method to mirror what will be available on the `Catalog` API.
> Remove get_pixels calls

- src/hipscat_import/catalog/arguments.py
Set the default `highest_healpix_order` parameter lower. This reduces the intermediate storage, and speeds most operations. For importing larger, denser catalogs, this will need to be overridden to a larger value, but for the majority of catalogs right now, 7 is sufficient.
> Set lower default import order.

- src/hipscat_import/soap/map_reduce.py
This is a little silly. Even though we'd like to remove `partition_info.csv` and `partition_join_info.csv`, they're required with the most recent version of the hipscat `Dataset` class. We need to be a valid dataset so we can release a new version of the hipscat library and still pass builds here.
> Add a partition_info on SOAP results.

- pyproject.toml
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/cross_match/macauff_arguments.py
- src/hipscat_import/cross_match/macauff_metadata.py
- src/hipscat_import/runtime_arguments.py
- tests/hipscat_import/conftest.py
- tests/hipscat_import/cross_match/test_macauff_metadata.py
- tests/hipscat_import/data/macauff/macauff_gaia_catwise_match.xml
- tests/hipscat_import/data/macauff/macauff_gaia_catwise_match_and_nonmatches.yaml
Part of Issue #147 - methods to convert macauff xml or yaml metadata files into parquet metadata files.
This also sneaks in a refactor of input file location to appease pylint.
> Initial commit of metadata file conversion

- src/hipscat_import/runtime_arguments.py
- src/hipscat_import/verification/arguments.py
- tests/hipscat_import/index/test_index_argument.py
- tests/hipscat_import/test_runtime_arguments.py
- tests/hipscat_import/verification/test_verification_arguments.py
Removes the check for the existence of the output directory when creating the runtime arguments, allowing for the full `catalog_path` to be created even if the base `output_path` does not exist. Closes #140.
> Create output directory

- tests/.pylintrc
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/conftest.py
This doesn't make any functional changes to the catalog import process. This just provides demonstration (proof?) of discussions around tweaking sort options during catalog import to achieve particular ordering of resulting parquet files.
> Add tests for more complex sorting scenarios.

- docs/notebooks/unequal_schema.ipynb
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/pipeline.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/run_soap.py
Fixes #172 .
My theory on what's going on here is that dask sees that it already has some completed tasks with the name `split_<k>`, and so doesn't even try to run them when they're encountered in the second pipeline execution. PR #173 tried to work around this issue by re-initializing the client to clear out the tasks, but that doesn't feel good/sustainable.
We *were* using the future's key to log completed stages after task success, but PR #143 took that out, so we can just let dask assign its own task keys.
> Remove the explicit task key.

- src/hipscat_import/catalog/map_reduce.py
- src/hipscat_import/index/map_reduce.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/index/test_run_index.py
One solution for issue #161  - sets the types of partitioning columns to:
- Norder: uint8
- Dir/Npix: uint64
> Specify types for partitioning columns.

- docs/catalogs/arguments.rst
- docs/catalogs/temp_files.rst
- docs/guide/contact.rst
- docs/index.rst
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/runtime_arguments.py
- tests/hipscat_import/catalog/test_run_import.py
Closes #120 
- Adds a new page in the documentation with (probably too much) information on temporary file creation
- Adds a distinction between tmp directory for intermediate parquet files, and (often) smaller resume files
- Does NOT add that distinction in the SOAP pipeline, just because I have some other in-flight changes there right now
> More text on temp. Split resume temp arg.

- .github/workflows/smoke-test.yml
- .github/workflows/testing-and-coverage.yml
- .github/workflows/type-checking.yml
- pyproject.toml
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/file_readers.py
- src/hipscat_import/catalog/map_reduce.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/runtime_arguments.py
- tests/hipscat_import/catalog/test_argument_validation.py
Addresses issues introduced from testing in #177 .
cloud tests will be added to https://github.com/astronomy-commons/hipscat-cloudtests in upcoming PRs.
> Pass storage options to read/write operations.

- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/margin_cache/margin_cache.py
- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
- tests/hipscat_import/test_runtime_arguments.py
Related to https://github.com/astronomy-commons/hipscat/issues/147
- Removes the `partition_info.csv` writing from catalog creation
- Writes out `_metadata` files for all created datasets
- Expands some tests to try loading the dataset after creation through import
- Suppresses the progress bar output in more unit tests
> Add metadata files when creating datasets

- tests/hipscat_import/index/test_run_index.py
I woke up bothered because something should have failed prior to https://github.com/astronomy-commons/hipscat-import/pull/189.
All Norder/Npix values happened to be the same because we were only testing with a primary catalog with a single Norder/Npix. Using a catalog with mixed Norder/Npix would fail when writing parquet metadata, unless setting `order_by_healpix=False`, which is added in PR #189.
> Add another test for creating index table.

- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
In the current margin cache generation, the values of the hive columns `NOrder`, `NPix`, and `Dir` are those from the margin's original pixel, and so do not match the hive values in the hipscat directory structure. This renames them to add the prefix `margin_`, ...,  and adds the hive columns that match the path to their pixel in the hipscat structure.
closes #188
> Rename Margin Cache Hive Columns

- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
Fixes a bug where generating a margin cache left the empty top level shard directories. 
Uses the existing `tmp_path` runtime argument that is maintained in the `RuntimeArguments` class, and is removed in the main pipeline after all other stages of the pipeline are complete.
> Use tmp_path in margin generation

- pyproject.toml
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/soap/run_soap.py
We've determined that loading from partition_info / partition_join_info CSVs is significantly faster than loading from _metadata, and this re-adds the generation of these files during catalog creation.
> Create partition info csvs on catalog creation.

- docs/catalogs/arguments.rst
- docs/conf.py
- docs/guide/contributing.rst
- docs/index.rst
- docs/requirements.txt
Adds a copy button to all code blocks in our readthedocs. 
:exploding_head: this also adds the copy button to all of the code blocks inside rendered notebooks. It's kind of wild.
see also: https://github.com/lincc-frameworks/python-project-template/pull/408
> Add copy button to readthedocs

- docs/catalogs/arguments.rst
- docs/conf.py
- docs/guide/contributing.rst
- docs/guide/index_table.rst
- docs/guide/margin_cache.rst
- docs/index.rst
- docs/requirements.txt
Gives all the help I can think to give when generating margin caches or index tables.
Note that this duplicates A LOT of the text between `catalogs/arguments.rst`, `guide/margin_cache.rst` and `guide/index_table.rst`. This is intentional, and based on feedback I got from Troy about duplicating some argument specifications instead of making users look in a few different places to put their pipeline together.
> Expand docs for margin and index generation.

- .github/workflows/code_style.yml
- pyproject.toml
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/margin_cache/__init__.py
- src/hipscat_import/pipeline.py
- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/catalog/test_file_readers.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/index/test_index_argument.py
- tests/hipscat_import/index/test_index_map_reduce.py
- tests/hipscat_import/margin_cache/test_arguments_margin_cache.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
- tests/hipscat_import/soap/test_run_soap.py
- tests/hipscat_import/test_runtime_arguments.py
> Mechanical application of black.

- src/hipscat_import/soap/arguments.py
- tests/hipscat_import/soap/test_run_soap.py
When running SOAP, the `write_leaf_files` argument did not correctly write the catalog_info parameter `contains_leaf_files`. This updates the soap arguments `to_catalog_info` method to include this.
> Fix soap arguments to catalog info not including all parameters

- docs/catalogs/public/sdss.rst
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/resume_plan.py
- src/hipscat_import/soap/run_soap.py
Related to https://github.com/astronomy-commons/lsdb/issues/167
Uses `tqdm.auto` to allow tqdm to pick between standard err output, and the prettier notebook output. This would just be a nice thing for users, if they're working inside a notebook, to have the prettier progress bars.
> Use auto mode for tqdm for nicer notebook render

- src/hipscat_import/soap/arguments.py
- src/hipscat_import/soap/map_reduce.py
- tests/hipscat_import/soap/test_run_soap.py
Closes #214. Closes #191 .
This forces the column names for SOAP output to be `object_id` and `source_id`. For other association tables, these fields could still be whatever they want to be.
> Force object and source ID in soap output.

- src/hipscat_import/pipeline_resume_plan.py
- tests/hipscat_import/catalog/test_resume_plan.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
- tests/hipscat_import/soap/test_soap_resume_plan.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #58. Closes #216 .
If the user specifies `resume=False`, then remove the intermediate directory instead of throwing an error. If we are resuming from prior state, give a warning (and catch this warning in testing, as it's a good indication that we've picked up some prior state and we're using it).
> If not resuming, remove intermediate dir.

- src/hipscat_import/index/map_reduce.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/pipeline.py
- tests/hipscat_import/index/test_index_map_reduce.py
- tests/hipscat_import/index/test_run_index.py
Closes #206.
- Performs the index de-duplication when reading from the original leaf file.
- Pass the dask client and use explicitly for the `compute` call.
> Index generation improvements

- src/hipscat_import/soap/map_reduce.py
- tests/hipscat_import/soap/test_run_soap.py
For most association between source-and-object, the two id values will be the same (since that's how we're finding the associations anyway). We don't need to keep those duplicate values around, and don't need to keep the `source_id` values around either.
> Drop duplicates in leaf files during SOAP.

- docs/catalogs/arguments.rst
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/run_import.py
- tests/hipscat_import/catalog/test_run_round_trip.py
> Add a lowest order argument.

- src/hipscat_import/catalog/file_readers.py
- src/hipscat_import/catalog/map_reduce.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/catalog/test_run_round_trip.py
Related to Issue #225. 
I wanted to speed up the ECSV reads by only reading the columns we need during the mapping stage. It's relevant for all kinds of file readers, though.
> Only read required columns in mapping stage.

- .gitattributes
- .github/workflows/pre-commit-ci.yml
- .github/workflows/smoke-test.yml
- README.md
- docs/guide/contributing.rst
Change links to other LINCC-related readthedocs pages to use en/stable instead of en/latest.
See https://github.com/astronomy-commons/lsdb/issues/260
> Change readthedocs URLs to stable

- docs/conf.py
Add cross-references to the hipscat library in the API documentation.
> Cross-link the hipscat docs

- docs/catalogs/public/index.rst
Closes #192.
Adds pointer to LSDB tutorials to import and work with a few publicly-available catalogs. 
NB: The links point to stable versions of the LSDB documentation, and the tutorials were recently moved to their new locations. The links won't work until the new version of LSDB is released.
> Direct to tutorials for public catalogs.

- pyproject.toml
- src/hipscat_import/catalog/run_import.py
- tests/conftest.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/conftest.py
Some tests are timing out (https://github.com/astronomy-commons/hipscat-import/actions/runs/8796038393/job/24148597886).
In debugging the issue, I figured it was just time to try to update to the latest dask version. This introduced some flakiness in the `client.scatter` when repeatedly scattering the same object. We can't reuse the scattered object between compute calls, so instead this forces the id to be unique between the two objects instead of re-using it.
> Update to latest dask to mitigate smoke test failures

- pyproject.toml
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/map_reduce.py
- tests/hipscat_import/catalog/test_run_round_trip.py
See https://github.com/astronomy-commons/lsdb/issues/294
See https://github.com/astronomy-commons/hipscat/pull/265
The `"**"` path part is only supported in the newest fsspec versions as an "entire path component", so it's ok to say `/match/like/**/` but not `/match/like/**.csv`. This should work with older and newer fsspec versions, and so once the change is released for only newer fsspec versions, this package should be ok.
> Use preferred string format for globbing.

- src/hipscat_import/pipeline_resume_plan.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #282 
Closes #273 
Fetches the traceback from the future's error field and prints out the available files, line numbers, and method names.
> Print tracebacks for nested errors.

- src/hipscat_import/catalog/file_readers.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/data/test_formats/gaia_epoch.ecsv
Closes #225 
Adds basic support for an ECSV reader. Note that the astropy ecsv reader does not implement a "fast" reader, so this method is not sped up by underlying C++, and it is not possible to chunk the reads into smaller tables.
See: https://docs.astropy.org/en/stable/io/ascii/read.html#reading-large-tables-in-chunks
> Add ECSV reader

- src/hipscat_import/catalog/map_reduce.py
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/sparse_histogram.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/catalog/test_resume_plan.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/catalog/test_sparse_histogram.py
Closes #154 using scipy.sparse for representation of healpix histogram.
Using the dense np array on-disk, the intermediate histograms for TIC are 8.5 G. Using sparse array, it's 48 M (around 200X improvement in disk usage). There's no discernible performance penalty.
> Use scipy.sparse for histogram storage.

- src/hipscat_import/catalog/file_readers.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/runtime_arguments.py
- tests/hipscat_import/catalog/test_resume_plan.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/soap/test_soap_resume_plan.py
Remove the warning from resume functionality. This should be an 'info' level message, but that's more of a logging notion than a true warning.
Allow a catalog name to include a `.`
Address new pylint warnings.
> Quick fixes (no warning, allow . in catalog name).

- src/hipscat_import/catalog/map_reduce.py
- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/data/small_sky_parts/catalog_10_of_05.csv
Closes #305 
Fixes an issue where `hipscat-import` throws an error when an input file is empty.
> Fix issue #305. Gracefully handle empty input files.

- .github/pull_request_template.md
- docs/catalogs/arguments.rst
- docs/conf.py
- docs/guide/contributing.rst
- docs/notebooks/estimate_pixel_threshold.ipynb
- docs/notebooks/unequal_schema.ipynb
- src/hipscat_import/catalog/file_readers.py
- add link to contribution guide and CoC in the pull request template
- add link to CoC in contribution guide
- fix import path in catalog import arguments in argument descriptions page
- set contribution guide to use `.setup_dev.sh` script
- remove mac-specific healpy installation (no longer needed)
- suggest larger threshold for slightly larger leaf parquet files on catalog import
- provider pointers to where input reader `kwargs` will be passed
> Assorted small doc fixes

- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- tests/hipscat_import/catalog/test_run_round_trip.py
Closes #297 
Exposes an existing internal testing parameter to keep the intermediate parquet shard files.
In addition, creates new option to keep the intermediate resume logging files.
> User arguments to retain intermediate files

- src/hipscat_import/catalog/file_readers.py
- tests/hipscat_import/catalog/test_file_readers.py
Closes #296 
Fixes a bug where `ParquetReader.read` takes a `read_columns` kwarg but doesn't actually use it.
- Pass the `read_columns` kwarg through to the read. This allows the mapping step to read only necessary columns (ra/dec) rather than all of them.
- Add a `column_names` class property. This allows the user to import only a subset of columns.
- Add unit test `test_parquet_reader_columns`.
> Apply `read_columns` kwarg in parquet reader

- src/hipscat_import/pipeline_resume_plan.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #299 
Converts paths to strings before performing comparison, so plain-text strings and Pathlib objects can be compared reasonably. Also, converts both sides into lists for comparisons.
> Spruce up the way we check for original input files.

- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/pipeline_resume_plan.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #300.
Adds code path for the waiting for futures operation to re-raise exception on the first exception encountered. The reducing stage is a little unique, in that a failure in *some* shard indicates that the whole pipeline may be experiencing issues, whereas failures at mapping and splitting are more likely to indicate a problem with an individual file.
> Fail fast on reduce stage failures.

- src/hipscat_import/catalog/map_reduce.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/map_reduce.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/soap/test_soap_map_reduce.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #301
Uses dask's distributed print call to log any exception encountered in tasks. This allows for some custom formatting, including the name of the input file, or reference to healpix shard.
> Print file name for mapping/splitting failures.

- src/hipscat_import/catalog/file_readers.py
- tests/hipscat_import/catalog/test_file_readers.py
The `storage_options` kwarg is very likely to contain sensitive user information, like API keys. Adds logic to suppress their storage in the `provenance_info.json` file.
> Redact storage options, as this may include user keys.

- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- src/hipscat_import/margin_cache/margin_cache_resume_plan.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache_resume_plan.py
Closes #313 .
Adds a resume plan to margin cache generation.
> Resume functionality for margin cache pipeline.

- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/margin_cache/margin_cache_arguments.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- src/hipscat_import/margin_cache/margin_cache_resume_plan.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/soap/arguments.py
- src/hipscat_import/soap/resume_plan.py
- src/hipscat_import/soap/run_soap.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache_resume_plan.py
A few clean-ups that don't change much functionality of resuming catalog, margin cache, or SOAP generation pipelines.
- Moves `delete_resume_log_files` up to the super class, so all resume plans can use the argument.
- Exposes user options for retaining intermediate files in margin generation and SOAP, as this was requested for catalog import and might be useful here as well.
- Moves margin cache pixel calculation more into the planning stages. Reduces the scope of the variables, and the negative pixel calculation can count toward the "planning" phase time.
- Only create directories for margin cache if the leaf files will be created.
> Tidy up some resume functionality

- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
With data re-generation on epyc, this closes #319.
Forces the use of the original catalog schema for reading and writing the input catalog parquet files. This coerces data types in the same way we do for catalog import, and ensures that dtypes are consistent between the original and margin catalogs.
> Use the original catalog schema in more reads/writes.

- requirements.txt
- src/hipscat_import/margin_cache/margin_cache_arguments.py
- tests/hipscat_import/margin_cache/test_arguments_margin_cache.py
Adds the catalog specific metadata ("epoch", "ra" and "dec") to the margin catalog info output. Closes #331.
> Update margin cache catalog info parameters

- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/catalog/test_file_readers.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/catalog/test_run_import.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/catalog/test_sparse_histogram.py
- tests/hipscat_import/conftest.py
- tests/hipscat_import/index/test_index_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
- tests/hipscat_import/soap/test_soap_map_reduce.py
- tests/hipscat_import/test_pipeline_resume_plan.py
- tests/hipscat_import/test_runtime_arguments.py
- tests/hipscat_import/verification/test_verification_arguments.py
This PR touches only files under tests/, and changes code to use pathlib.Path for constructing test data paths, instead of `os.path.join`.
This shouldn't change any functionality, but is just cleaner.
> Use pathlib for pytest fixtures.

- docs/catalogs/arguments.rst
- src/hipscat_import/catalog/file_readers.py
- tests/hipscat_import/catalog/test_file_readers.py
- tests/hipscat_import/catalog/test_run_round_trip.py
- tests/hipscat_import/conftest.py
- tests/hipscat_import/data/indexed_files/csv_list_double_1_of_2.txt
- tests/hipscat_import/data/indexed_files/csv_list_double_2_of_2.txt
- tests/hipscat_import/data/indexed_files/csv_list_single.txt
- tests/hipscat_import/data/indexed_files/parquet_list_single.txt
Closes #308 .
Creates a new kind of file reader for catalog import: indexed file reader. This uses a single "index" file as a task unit, and these files contain only paths to data files to be read. This enables batching many small input data files into larger chunks for the map and reduce stages of the pipeline. 
Implements an indexed reader for CSV and for Parquet files. In particular, the parquet reader utilizes pyarrow's parquet read `batch_readahead`, `fragment_readahead`, and multi-threading to further speed up reads of many small data files.
> Enable "index file" reads for catalog import

- docs/catalogs/arguments.rst
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/margin_cache/margin_cache_resume_plan.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/runtime_arguments.py
- src/hipscat_import/soap/resume_plan.py
- src/hipscat_import/soap/run_soap.py
- tests/hipscat_import/test_pipeline_resume_plan.py
Closes #327.
Consolidates all `tqdm` calls into re-used `print_progress` method. This way, the `simple_progress_bar` argument will work the same for all pipeline types.
> Enable std tqdm bar, refactor for re-use.

- src/hipscat_import/catalog/file_readers.py
- tests/hipscat_import/catalog/test_file_readers.py
Closes #335 .
When passing `read_columns` (as in the mapping stage), do not attempt to further limit the columns read from the fits file.
> Only specify the astropy table columns once.

- pyproject.toml
Require latest version of hipscat, for margin catalog metadata.
> Require recent hipscat

- src/hipscat_import/catalog/file_readers.py
- tests/hipscat_import/catalog/test_argument_validation.py
Closes #342 
The kwarg for column names was being stored as the index of the pandas dataframe representing the parquet schema. This was unnecessary, as we only need the list of column names.
> Use list of names, instead of pandas index.

- pyproject.toml
- src/hipscat_import/catalog/map_reduce.py
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/sparse_histogram.py
- src/hipscat_import/margin_cache/margin_cache_arguments.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- src/hipscat_import/soap/resume_plan.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/conftest.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
See https://github.com/astronomy-commons/hipscat/issues/53 and https://github.com/astronomy-commons/hipscat/pull/297
Uses the healpix shim methods for any healpy calls.
> Use hipscat for healpix dependency.

- src/hipscat_import/catalog/file_readers.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- src/hipscat_import/soap/map_reduce.py
Related to [hipscat ](https://github.com/astronomy-commons/hipscat/issues/309)
Removes uses of `load_parquet_to_pandas` in favor of `read_parquet_file_to_pandas`
> Use consistent pandas file io method.

- requirements.txt
- src/hipscat_import/index/map_reduce.py
- src/hipscat_import/soap/arguments.py
- src/hipscat_import/soap/map_reduce.py
Provide the arrow schema to reading of parquet files in index and soap pipelines.
> Read parquet files with arrow schema

- src/hipscat_import/catalog/file_readers.py
Use appropriate scope for pandas chunk reading generator, with file-ownership in hipscat method.
> Fix CSV reader from recent changes in hipscat library

- docs/requirements.txt
- src/hipscat_import/soap/map_reduce.py
Adds the arrow schema as an argument to the parquet reading of the source data files in the SOAP pipeline, which I missed in https://github.com/astronomy-commons/hipscat-import/pull/348. It also fixes the documentation build, which is failing, by installing `hipscat` from source.
> Add schema to source data in SOAP pipeline

- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- tests/hipscat_import/catalog/test_map_reduce.py
- tests/hipscat_import/catalog/test_resume_plan.py
- tests/hipscat_import/catalog/test_run_round_trip.py
Closes https://github.com/astronomy-commons/hipscat/issues/302
Closes #269
Adds `drop_empty_siblings` argument to binning calculation, as added in https://github.com/astronomy-commons/hipscat/pull/304.
Increases the default `highest_order` s.t. users are unlikely to need to change it, and clarifies behavior in the docstrings.
> Provide `drop_empty_siblings` argument

- src/hipscat_import/margin_cache/margin_cache_arguments.py
- tests/hipscat_import/margin_cache/test_arguments_margin_cache.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_cache_resume_plan.py
Change the algorithm selecting the default margin order value: from being the smallest possible value (largest order of the catalog plus one) to be the largest possible value (so tiles would still include all objects within a given margin threshold).
Fixes #358
> Change default margin order

- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/runtime_arguments.py
- tests/hipscat_import/catalog/test_argument_validation.py
Closes #341.
It's pretty common for users to use the result of a glob operation as input in the `input_file_list` argument. If the glob expression is mal-formed and the results are empty, they'll get a confusing error. This distinguishes the behavior from not passing in anything to hopefully give a more helpful message.
> Distinguish error message for empty list vs None.

- src/hipscat_import/__init__.py
- tests/hipscat_import/test_packaging.py
Adds the \_\_version\_\_ property to show the installed package version. Closes #347.
> Add package version property

- .github/workflows/publish-to-pypi.yml
- MANIFEST.in
This pull request updates the `publish-to-pypi.yml` workflow, which runs on each package release, to include a file with the list of installed requirements at the time of publishing. Also, according to the following https://github.com/astronomy-commons/hipscat-import/issues/362#issuecomment-2278864308, I added an extra verification step to the pipeline, running the unit tests prior to packaging. Closes #362.
The requirements file helps recreate environments with consistent transitive dependencies, and make deployments on Dask Kubernetes clusters reproducible. When installing `hipscat-import` on a Docker image one should:
```bash
$ pip download hipscat-import --no-deps --no-binary :all: # download the sdist
$ tar -xzf hipscat-import* # unzip it
$ cd hipscat-import*/
$ pip install -r …
```
> Bundle dependency requirements with release

- README.md
Update LINCC logo with 2024 version as requested in https://github.com/astronomy-commons/lsdb/issues/403
> Update LINCC logo with 2024 version

- .copier-answers.yml
- .github/ISSUE_TEMPLATE/1-bug_report.md
- .github/workflows/asv-main.yml
- .github/workflows/asv-nightly.yml
- .github/workflows/asv-pr.yml
- .github/workflows/publish-benchmarks-pr.yml
- .pre-commit-config.yaml
- benchmarks/asv.conf.json
- benchmarks/benchmarks.py
- pyproject.toml
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/sparse_histogram.py
- tests/hipscat_import/catalog/test_run_import.py
First stage of binning process reads all partial histogram files and combines them into a single histogram. This was initially written to combine the histograms as sparse arrays, but this can be very expensive, so just flatten out the arrays as we're combining them.
NB: I've added benchmarks with copier, so this also updates the copier version and other associated changes.
> Benchmark and speed up to first stage of binning.

- docs/catalogs/arguments.rst
- docs/guide/index_table.rst
- docs/guide/margin_cache.rst
- pyproject.toml
- src/hipscat_import/catalog/arguments.py
- src/hipscat_import/catalog/file_readers.py
- src/hipscat_import/catalog/map_reduce.py
- src/hipscat_import/catalog/resume_plan.py
- src/hipscat_import/catalog/run_import.py
- src/hipscat_import/index/arguments.py
- src/hipscat_import/index/map_reduce.py
- src/hipscat_import/index/run_index.py
- src/hipscat_import/margin_cache/margin_cache.py
- src/hipscat_import/margin_cache/margin_cache_arguments.py
- src/hipscat_import/margin_cache/margin_cache_map_reduce.py
- src/hipscat_import/margin_cache/margin_cache_resume_plan.py
- src/hipscat_import/pipeline_resume_plan.py
- src/hipscat_import/runtime_arguments.py
- src/hipscat_import/soap/arguments.py
- src/hipscat_import/soap/map_reduce.py
- src/hipscat_import/soap/resume_plan.py
- src/hipscat_import/soap/run_soap.py
- src/hipscat_import/verification/arguments.py
- tests/hipscat_import/catalog/test_argument_validation.py
- tests/hipscat_import/catalog/test_resume_plan.py
- tests/hipscat_import/margin_cache/test_margin_cache.py
- tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
- tests/hipscat_import/margin_cache/test_margin_round_trip.py
- tests/hipscat_import/soap/test_soap_map_reduce.py
- tests/hipscat_import/verification/test_verification_arguments.py
See https://github.com/astronomy-commons/hipscat/pull/336
Use fsspec's project, [universal-pathlib](https://github.com/fsspec/universal_pathlib) as a path provider. In this way, everywhere we currently pass in a `FilePointer` we can use a `Path` instead, and when we need to create remote connections, use `UPath`.
> Replace FilePointer with universal pathlib

- src/hats_import/hipscat_conversion/run_conversion.py
In a former PR, https://github.com/astronomy-commons/hipscat-import/pull/392, I made a suggestion to use the `:=` operator.  This obviates the line following, but I wasn't able to make that line deletion part of my suggestion.  This PR follows up on that suggestion, as well as defaulting the other `None` arguments to `.get()` in the following clause.
> Style follow-up on run_conversion.py

- .github/workflows/pre-commit-ci.yml
- .github/workflows/testing-and-coverage.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/hats_import/catalog/arguments.py
- src/hats_import/catalog/map_reduce.py
- src/hats_import/catalog/resume_plan.py
- src/hats_import/hipscat_conversion/run_conversion.py
- src/hats_import/margin_cache/margin_cache_arguments.py
- src/hats_import/margin_cache/margin_cache_resume_plan.py
- src/hats_import/runtime_arguments.py
- src/hats_import/soap/arguments.py
- src/hats_import/soap/resume_plan.py
- tests/hats_import/hipscat_conversion/test_run_conversion.py
- tests/hats_import/soap/test_run_soap.py
**Note**
In the course of fixing this, I found many linting issues that have crept in over the course of this branch, because we haven't had CI running on PRs for this branch! This addresses the findings, and turns on branch CI (just in time for the very last few PRs...)
> Update size estimate on converted catalog.

- .github/workflows/publish-to-pypi.yml
See action failure: https://github.com/astronomy-commons/hats-import/actions/runs/11386003133
We're unable to publish to pypi because we `pip install` the package locally. We do this in order to resolve dependencies and create a requirements.txt file.
This attempts a work-around to generate the requirements file, and remove the locally built package.
> Remove locally-created package before publishing.

- src/hats_import/catalog/map_reduce.py
- src/hats_import/margin_cache/margin_cache_map_reduce.py
- src/hats_import/margin_cache/margin_cache_resume_plan.py
- tests/hats_import/catalog/test_map_reduce.py
Fixes a failing unittest due to unstable sorting.
> Use stable sorts when sorting by the index

- .github/workflows/publish-to-pypi.yml
See reasoning and more details at https://github.com/astronomy-commons/hats-import/pull/409
> Create virtual environment and ignore changes to requirements file.

- src/hats_import/hipscat_conversion/run_conversion.py
- tests/hats_import/hipscat_conversion/test_run_conversion.py
Pandas metadata uses the old `_hipscat_id` field. Instead of manipulating the pandas metadata to fit new columns, just remove from the parquet schema.
> Remove pandas metadata in hipscat conversion

- pyproject.toml
Constrains Dask to version `<2024.11.0` because of issue reported in https://github.com/ray-project/ray/issues/48689.
> Constrain Dask version

- src/hats_import/catalog/map_reduce.py
- src/hats_import/hipscat_conversion/run_conversion.py
- src/hats_import/margin_cache/margin_cache_map_reduce.py
- tests/hats_import/catalog/test_map_reduce.py
- tests/hats_import/margin_cache/test_margin_cache_map_reduce.py
Requires https://github.com/astronomy-commons/hats/pull/432
> Use radec2pix for healpix pixel calculation.

- docs/index.rst
- src/hats_import/hipscat_conversion/run_conversion.py
- tests/hats_import/hipscat_conversion/test_run_conversion.py
See https://github.com/astronomy-commons/hats/pull/433
We still need the `healpy` library to occasionally read older FITS files that may have been written in RING pixelization. Marked as optional dependency, and tests can still run against it if healpy is installed.
> Remove default healpy dependency.

- src/hats_import/hipscat_conversion/run_conversion.py
See https://github.com/astronomy-commons/hats-import/issues/434
Existing margins may have missed many points when generated. Don't allow blind conversion from hipscat -> hats.
> Force re-creation of margin catalog.

- .github/workflows/testing-windows.yml
Now that we don't depend on healpy, everything should run well on Windows. This adds a test to confirm that.
See https://github.com/astronomy-commons/hats/pull/440
> Test on Windows OS.

- docs/catalogs/arguments.rst
- docs/catalogs/temp_files.rst
- docs/guide/contact.rst
- docs/guide/contributing.rst
- docs/guide/hipscat_conversion.rst
- docs/guide/index_table.rst
- docs/guide/margin_cache.rst
- 'overwrite' param has been removed
- expand contact information; include calendar widget
- similar updates to contribution guide from https://github.com/astronomy-commons/lsdb/pull/531
- use new `aggregate_column_statistics` for index division estimation
> Documentation improvements

- src/hats_import/catalog/run_import.py
- src/hats_import/margin_cache/margin_cache.py
- tests/hats_import/catalog/test_run_import.py
Strong refusal without options, since it's easier and safer to move the catalog out of the way.
Before beginning a catalog import or generating a margin cache, check whether the output artifact already contains a valid catalog, and if so, stop by raising a `ValueError`.
Closes #459 .
Tested this end-to-end on epyc, and verified it, and added unit tests to verify argument validation.
> Avoid overwriting valid catalogs.

- src/hats_import/catalog/map_reduce.py
- src/hats_import/catalog/resume_plan.py
- tests/hats_import/catalog/test_resume_plan.py
- tests/hats_import/catalog/test_run_import.py
We really just need the non-zero indexes and non-zero values, and the complexity of the general scipy sparse array is adding a lot of compute overhead, primarily in the catalog import "Binning" stage.
https://github.com/astronomy-commons/hats/pull/446
> Use a naive sparse histogram.

- src/hats_import/catalog/run_import.py
- src/hats_import/margin_cache/margin_cache.py
- src/hats_import/runtime_arguments.py
- tests/hats_import/catalog/test_argument_validation.py
- tests/hats_import/catalog/test_run_import.py
- tests/hats_import/catalog/test_run_round_trip.py
- tests/hats_import/margin_cache/test_arguments_margin_cache.py
- tests/hats_import/test_runtime_arguments.py
See also #459 and #464
Moves check for existing valid catalog to earlier in the argument checks.
> Move existing catalog check.

- src/hats_import/catalog/resume_plan.py
- src/hats_import/margin_cache/margin_cache_resume_plan.py
- src/hats_import/pipeline_resume_plan.py
- src/hats_import/soap/resume_plan.py
- tests/hats_import/catalog/test_resume_plan.py
- tests/hats_import/test_pipeline_resume_plan.py
The current strategy of reading strings from file names, passing along those strings, and manually performing `not in` against constructed strings was taking foooorrrrreeeevvvveeeerrrrr in cases where there are 100k+ stages. This streamlines those operations, using integers and set operations where possible.
> Address slow list operations in progress tracking.

- docs/catalogs/public/sdss.rst
Minor details noticed in the docs
Part of astronomy-commons/lsdb#540
> Update code snippet in sdss.rst

- docs/catalogs/public/index.rst
- src/hats_import/pipeline_resume_plan.py
See: https://github.com/astronomy-commons/lsdb/issues/541
- Give (only slightly) more friendly error message when some stages of the import task fail
- Clarify that the "public catalogs" page is just tips for various catalogs
- Provide link to data.lsdb.io
- Fix doc links for import notebooks
> Suggested changes from science homework.

- docs/catalogs/arguments.rst
- docs/catalogs/properties.rst
- docs/index.rst
Expose documentation about the available automatic and user-provided properties of HATS catalogs.
> Add more detail about available HATS properties on import.

- docs/guide/contact.rst
Changes LSSTC to LSST Discovery Alliance in our contact section of the Documentation.
> LSSTC to LSST Discovery Alliance

- src/hats_import/catalog/arguments.py
- src/hats_import/catalog/map_reduce.py
- src/hats_import/catalog/run_import.py
- tests/hats_import/catalog/test_run_import.py
- tests/hats_import/catalog/test_run_round_trip.py
Closes #516, #517.
Related to #513.
Passes additional kwarg dictionaries through the import pipeline to use when writing the final parquet tables. 
- `write_table_kwargs` set is passed directly to the `write_table` call, and can specify values for compression
- `row_group_kwargs` defines the row group splitting strategy to use for the parquet files. currently the only strategy supported is the current sort column.
> Pass additional kwargs through import

- src/hats_import/catalog/map_reduce.py
- tests/hats_import/catalog/test_run_round_trip.py
Add two row group splitting strategies, `num_rows` and `subtile_order_delta`. 
The first one allows to specify a number of rows per row group (e.g. `row_group_kwargs={"num_rows": 100}`). The second allows to specify how many times we should split a destination pixel, each HEALPix split results in a row group at a higher order (e.g. `row_group_kwargs={"subtile_order_delta": 2}`). 
I am also passing the `sort_columns` to the parquet metadata, which is useful for parquet readers.
> Configure row group splitting strategies

- src/hats_import/index/map_reduce.py
- tests/hats_import/catalog/test_file_readers.py
- tests/hats_import/catalog/test_run_round_trip.py
- tests/hats_import/hipscat_conversion/test_run_conversion.py
- tests/hats_import/index/test_run_index.py
New nested pandas I/O doesn't support different pandas dtype backends, so tests are changed to remove the different backend dtypes and always check for arrow types
> Support nested pandas I/O in latest hats

- src/hats_import/catalog/run_import.py
- src/hats_import/hipscat_conversion/run_conversion.py
- tests/hats_import/catalog/test_run_import.py
- tests/hats_import/hipscat_conversion/test_run_conversion.py
- tests/hats_import/margin_cache/test_margin_cache.py
Create the data thumbnail parquet in the pipeline for main object/source catalogs.
> Generate data thumbnail in the import pipelines

- src/hats_import/runtime_arguments.py
- src/hats_import/verification/arguments.py
- tests/hats_import/catalog/test_run_round_trip.py
- tests/hats_import/verification/test_verification_arguments.py
Checks against middle-directories are not useful on Google Cloud Storage file system, as these paths don't really exist. AWS pretends they do, but GCS does not. The checks that are failing aren't particularly useful, and the missing files/directories are caught elsewhere.
> Remove directory-specific checks.

- docs/catalogs/collections.rst
- docs/catalogs/file_readers.rst
- docs/citation.rst
- docs/getting_started.rst
- docs/index.rst
- docs/pre_executed/backport_collection.ipynb
In advance of writing some more documentation pages for HATS-import, I wanted to clean up the home page and navigation.
- Give a warning that folks might want to look at LSDB instead.
- Move acknowledgements into `citation.rst`, and add citation text
- Move up the `Contact` page in the TOC - 
- Move installation and quick start to separate page
- add the TOC to the home page to encourage a particular sequence of reading
- Break out the most typical pages folks will need to create a catalog from the more niche customization
- placeholders for new documentation pages.
> Re-arrange import documentation.

- src/hats_import/collection/arguments.py
- tests/hats_import/collection/test_collection_arguments.py
- tests/hats_import/collection/test_collection_import.py
Closes #565 
Two behaviors should be covered by this PR:
- a previous execution was successful and there is already a collection at the provided path
- should still create the new supplemental tables
- existing tables should not spawn sub-pipelines
- collection properties should be appended, instead of overwritten
- a previous execution was partially successful, and there are supplemental tables present
- new supplemental tables should be written
- existing tables should not spawn sub-pipelines
- a new collection properties should be written, that includes all supplemental tables
> Check for existing supplemental tables in collection import.

- src/hats_import/catalog/arguments.py
- src/hats_import/catalog/run_import.py
- tests/hats_import/catalog/test_run_import.py
While importing DES shape catalog, the finishing step took as long as the rest of the pipeline combined:
```
Planning  : 100%|██████████| 4/4 [00:00<00:00, 781.75it/s]
Mapping   : 100%|██████████| 400/400 [00:29<00:00, 13.46it/s]
Binning   : 100%|██████████| 2/2 [00:57<00:00, 28.54s/it]
Splitting : 100%|██████████| 400/400 [17:03<00:00,  2.56s/it]  
Reducing  : 100%|██████████| 1051/1051 [09:07<00:00,  1.92it/s] 
Finishing : 100%|██████████| 5/5 [25:25<00:00, 305.04s/it]   
```
I believe that most of this is in creating the thumbnail. Since we don't have immediate plans to use this data (and it can be recreated from the catalog at any time), I'm setting the default to not generate the thumbnail just yet.
> Make thumbnail generation optional.

- .github/dependabot.yml
- pyproject.toml
Prevent dependabot PRs from regressing due to known version pins.
For specific, strategic version pinning instructions, leave notes to maintainers in the dependency file *and* adjust the `dependabot` configuration with the same notes.
> Add strategic version pinning instructions
