astronomy-commons/hats-import

.copier-answers.yml
.github/workflows/python-package.yml
.gitignore
pyproject.toml

Use the LINCC Frameworks project template at https://github.com/lincc-frameworks/python-project-template

Use copier to keep up with best practices

---

src/hipscat_import/arguments.py
src/hipscat_import/map_reduce.py
src/hipscat_import/run_import.py

Some are addressed by ignoring them for now.

Address pylint issues.

---

src/hipscat_import/map_reduce.py
tests/hipscat_import/test_map_reduce.py

Remove unneccessary client creation in unit tests.

Fix indexing when filtering.

---

src/hipscat_import/catalog/file_readers.py

See https://github.com/astronomy-commons/hipscat-import/actions/runs/4597738077

Use pandas 2.0.0 arguments.

---

.copier-answers.yml
.github/workflows/build-documentation.yml
.github/workflows/linting.yml
.github/workflows/publish-to-pypi.yml
.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
.github/workflows/type-checking.yml
.pre-commit-config.yaml
LICENSE
README.md

- Run copier
- Add LINCC Frameworks Schmidt Futures Acknowledgement to README
- Add workflow dispatch to smoke test

Straightforward updates.

---

src/hipscat_import/catalog/arguments.py
src/hipscat_import/catalog/run_import.py
src/hipscat_import/pipeline.py

- Allow larger pixel thresholds
- Improve behavior when some stages fail

Checkpoint some quality-of-life fixes

---

docs/catalogs/arguments.rst
src/hipscat_import/catalog/file_readers.py

Add some configuration documentation that I would have found useful.

Add some documentation

---

pyproject.toml

keep `hipscat` dependency on 0.1.0 for now to avoid breaking CI.
step 2 of #103 
used `< 0.1.1` because I wasn't sure how pip would handle setting it explicitly to `0.1.0` when the official version number in pypi is `0.1` 😅 
_technicallyyy_ the version hasn't changed as we're still just using the same one we were before. also this is temporary 🥲

pin hipscat dependency to 0.1.0 to avoid compatibility changes

---

src/hipscat_import/catalog/resume_plan.py
src/hipscat_import/pipeline_resume_plan.py
tests/hipscat_import/catalog/test_resume_plan.py
tests/hipscat_import/test_pipeline_resume_plan.py

Pull all helper logic out of the current catalog resume plan into a common dataclass. This logic will be reused in the SOAP resume implementation.

Prefactor resume plan logic.

---

docs/requirements.txt
pyproject.toml

unpins the `sphinx` versions to preempt autodoc failures we've had with other PPT repos :)

unpin sphinx versions

---

.copier-answers.yml
.github/workflows/build-documentation.yml
.github/workflows/linting.yml
.github/workflows/pre-commit-ci.yml
.github/workflows/type-checking.yml
.gitignore
.pre-commit-config.yaml
docs/guide/contributing.rst
pyproject.toml
src/.pylintrc
tests/.pylintrc

Runs copier update to use new template version. Moves the new "getting started dev guide" to expand on environment setup instructions in the contribution guide.

Update to PPT v1.4.3

---

src/hipscat_import/catalog/resume_plan.py
src/hipscat_import/pipeline_resume_plan.py
src/hipscat_import/soap/resume_plan.py
tests/hipscat_import/catalog/test_resume_plan.py
tests/hipscat_import/soap/test_soap_resume_plan.py
tests/hipscat_import/test_pipeline_resume_plan.py

Check for success artifacts after each stage.

---

pyproject.toml

for #150 , but don't close out the issue until we pyarrow updates and we can remove the pins.
pin `fsspec` version

pin fsspec

---

src/hipscat_import/catalog/file_readers.py

Instead of reading the whole parquet file into memory as a pyarrow table, this PR reads it lazily.

Read parquet lazily

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
.github/workflows/type-checking.yml

Scoot python versions forward (#182)

---

.copier-answers.yml
.git_archival.txt
.gitattributes
docs/conf.py
docs/requirements.txt
pyproject.toml

See [release notes](https://github.com/lincc-frameworks/python-project-template/releases/tag/v1.4.6) for updates.

Apply template v.1.4.6

---

pyproject.toml
src/hipscat_import/catalog/arguments.py
src/hipscat_import/index/arguments.py
src/hipscat_import/margin_cache/margin_cache_arguments.py
src/hipscat_import/runtime_arguments.py
src/hipscat_import/soap/arguments.py
src/hipscat_import/verification/arguments.py
tests/hipscat_import/catalog/test_run_round_trip.py

Requires https://github.com/astronomy-commons/hipscat/pull/219
Closes #228 , Closes #160.

Add tests that we can handle pathlib.Path.

---

.copier-answers.yml
.github/ISSUE_TEMPLATE/2-feature_request.md
.github/workflows/smoke-test.yml
.setup_dev.sh
docs/requirements.txt
pyproject.toml

Updates copier template to PPT v2.0

Apply PPT v2.0

---

docs/catalogs/arguments.rst
docs/catalogs/public/allwise.rst
docs/catalogs/public/neowise.rst
src/hipscat_import/catalog/file_readers.py
tests/hipscat_import/catalog/test_file_readers.py
tests/hipscat_import/catalog/test_map_reduce.py
tests/hipscat_import/catalog/test_run_round_trip.py

Improve handling of kwargs for reading parquet schema (to use for column names/types), and for reading CSV file.

Improve CSV reading kwargs

---

docs/requirements.txt

See also https://github.com/astronomy-commons/lsdb/pull/222

Require ipywidgets

---

docs/_static/custom.css
docs/conf.py
docs/requirements.txt

Changes the sphinx theme to [sphinx book theme](https://sphinx-book-theme.readthedocs.io/en/stable/index.html)

Change sphinx theme to book theme

---

pyproject.toml
src/hipscat_import/index/arguments.py
src/hipscat_import/index/map_reduce.py
src/hipscat_import/index/run_index.py
src/hipscat_import/margin_cache/margin_cache.py
src/hipscat_import/margin_cache/margin_cache_arguments.py
src/hipscat_import/margin_cache/margin_cache_map_reduce.py
src/hipscat_import/soap/arguments.py
src/hipscat_import/soap/map_reduce.py
src/hipscat_import/soap/resume_plan.py
src/hipscat_import/soap/run_soap.py
tests/hipscat_import/margin_cache/test_margin_cache.py
tests/hipscat_import/margin_cache/test_margin_cache_map_reduce.py
tests/hipscat_import/soap/test_run_soap.py
tests/hipscat_import/soap/test_soap_map_reduce.py

Addresses problems reading from and writing to cloud buckets during index, margin, and SOAP generation.

Use storage options for input and output

---

.copier-answers.yml
pyproject.toml

copier update

---

docs/guide/margin_cache.rst

The name of the catalog in the example was inconsistent with the default value of the margin cache threshold. I add an explicit `margin_threshold` argument to make the example correct

Docs: margin_threshold in margin_cache.rst

---

README.md
docs/index.rst

Augment acknowledgement and add to RTD.

Update acknowledgment text.

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
pyproject.toml

See also:
https://github.com/astronomy-commons/lsdb/pull/289
https://github.com/astronomy-commons/lsdb/issues/270
https://github.com/astronomy-commons/lsdb/issues/285

Update python and hipscat version pins.

---

src/hipscat_import/catalog/file_readers.py

Closes #304 
Relies on astronomy-commons/hipscat#274
Updates the `provenance_info` method of the base class `InputReader` to return all class attributes. Removes the method from child classes.
This picks up attributes that were not previously being captured and results in some tests failing when the values cannot be json serialized. As far as I can tell, the best place to handle this is in `hipscat.io.write_metadata.HipscatEncoder` so I opened astronomy-commons/hipscat#274 to address it. Using that on my local machine, all tests pass.

Get all file_reader provenance info programmatically

---

src/hipscat_import/soap/run_soap.py

Return value added in https://github.com/astronomy-commons/hipscat/pull/306

Use total returned from write_parquet_metadata

---

pyproject.toml

Require most recent hipscat version, for schema changes.

Require recent hipscat

---

src/hats_import/pipeline.py

Allows to run the hipscat conversion pipeline from the main pipeline script.

Run conversion from main pipeline script.

---

pyproject.toml
src/hats_import/index/arguments.py
src/hats_import/margin_cache/margin_cache_arguments.py
src/hats_import/soap/arguments.py
src/hats_import/soap/resume_plan.py
src/hats_import/verification/arguments.py
tests/hats_import/catalog/test_run_import.py
tests/hats_import/catalog/test_run_round_trip.py
tests/hats_import/index/test_run_index.py
tests/hats_import/margin_cache/test_margin_cache.py
tests/hats_import/margin_cache/test_margin_cache_resume_plan.py
tests/hats_import/margin_cache/test_margin_round_trip.py
tests/hats_import/soap/test_run_soap.py
tests/hats_import/soap/test_soap_resume_plan.py
tests/hats_import/verification/test_verification_arguments.py

Type-specific calls removed in PR https://github.com/astronomy-commons/hats/pull/394

Fix calls to read_hats

---

docs/guide/hipscat_conversion.rst
docs/index.rst

Basic documentation for HiPSCat->HATS conversion pipeline.

Helper documentation for hipscat conversion

---

.github/workflows/pre-commit-ci.yml
.github/workflows/testing-and-coverage.yml
requirements.txt
src/hats_import/margin_cache/margin_cache_arguments.py
src/hats_import/margin_cache/margin_cache_map_reduce.py
tests/hats_import/margin_cache/test_margin_cache.py
tests/hats_import/margin_cache/test_margin_cache_map_reduce.py
tests/hats_import/margin_cache/test_margin_round_trip.py

Temporarily remove fine filtering.
See https://github.com/astronomy-commons/hats-import/issues/434

Remove margin fine filtering.

---

pyproject.toml

See https://github.com/astronomy-commons/lsdb/issues/516

Require new hats

---

.copier-answers.yml
.github/workflows/build-documentation.yml
.github/workflows/pre-commit-ci.yml
.github/workflows/publish-to-pypi.yml
.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
.pre-commit-config.yaml
.readthedocs.yml
docs/index.rst
pyproject.toml
src/.pylintrc
tests/.pylintrc

Support dropped in hats. See https://github.com/astronomy-commons/hats/pull/442

Drop support for python 3.9

---

docs/catalogs/arguments.rst
docs/guide/verification.rst

Update RTD links

---

src/hats_import/catalog/arguments.py
tests/hats_import/catalog/test_run_round_trip.py
tests/hats_import/margin_cache/test_margin_round_trip.py

Enable drop_empty_siblings by default

---

src/hats_import/collection/__init__.py
src/hats_import/collection/arguments.py
src/hats_import/collection/run_import.py
src/hats_import/pipeline.py
src/hats_import/runtime_arguments.py
tests/hats_import/collection/test_collection_arguments.py
tests/hats_import/collection/test_collection_import.py

Pipeline to create catalog collections

---

docs/notebooks.rst
docs/pre_executed/backport_collection.ipynb

Documentation for creating collection from existing catalog.

---

src/hats_import/catalog/arguments.py
src/hats_import/catalog/run_import.py
tests/hats_import/catalog/test_run_round_trip.py

Requires https://github.com/astronomy-commons/hats/pull/511
Closes #557

Write skymap.fits and alternative orders

---

src/hats_import/catalog/map_reduce.py
tests/hats_import/catalog/test_map_reduce.py
tests/hats_import/collection/test_collection_import.py

Partial solution to #569. 
See also: https://github.com/astronomy-commons/hats/pull/539

Check for corrupted file if resuming reduce step.

---

pyproject.toml

https://github.com/astronomy-commons/lsdb/issues/1023

Update hats pins

---

pyproject.toml

Keeping in version lockstep with `hats v0.6.6`.

Update hats dependency version to 0.6.6
